# This file was *autogenerated* from the file Experiment1.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_0p000000000000000000000000001 = RealNumber('0.000000000000000000000000001'); _sage_const_10 = Integer(10); _sage_const_30 = Integer(30); _sage_const_50 = Integer(50)
import random
import ValueIteration
import ValueIteration2
import MMCDiscreteUnbiased
reload(MMCDiscreteUnbiased)
reload(ValueIteration)
reload(ValueIteration2)

if __name__ == "__main__":

    while True:
        p = plot([],axes_labels = ['$\lambda$','Total Cost'])
        colors = rainbow(_sage_const_30 )
        MDP_Plot_Data = []
        MDP_Plot_Data2 = []
        DiscretePlotData = []

        testmu = random.uniform(_sage_const_5 ,_sage_const_10 )
        testC = random.randint(_sage_const_1 ,_sage_const_5 )
        testR = random.uniform(_sage_const_1 ,_sage_const_10 )

        for e in range(_sage_const_1 ,_sage_const_50 ):
            print "Testing %s" %(e)

            MDP = ValueIteration.Queue(lmbda = e, mu = testmu ,C = testC,R = testR,epsilon = _sage_const_0p000000000000000000000000001 )
            MDPVal = MDP.ValueIter()

            MDP2 = ValueIteration2.Queue(lmbda = e, mu = testmu ,C = testC,R = testR,epsilon = _sage_const_0p000000000000000000000000001 )
            MDPVal2 = MDP2.ValueIter()

#            DiscreteTrials = [MMCDiscreteUnbiased.DiscreteSim(lmbda = e,mu = testmu,C = testC ,Reward = testR,Policy = MDPVal[1],Simulation_Time = 200,warm_period = 50) for k in range(500) ]
 #           DiscreteAve = sum(DiscreteTrials)/len(DiscreteTrials)

   #         DiscretePlotData.append([e,DiscreteAve])
            MDP_Plot_Data.append([e,MDPVal[_sage_const_0 ]])
            MDP_Plot_Data2.append([e,MDPVal2[_sage_const_0 ]])


            if len(MDP_Plot_Data) == _sage_const_1 :
                p += line(MDP_Plot_Data,color = 'red',legend_label = 'MDP' )
                p += line(MDP_Plot_Data2,color = 'green',legend_label = 'MDP2' )
  #              p += line(DiscretePlotData,color = 'blue', legend_label = 'Discrete Sim')
            else:
                p += line(MDP_Plot_Data,color = 'red')
                p += line(MDP_Plot_Data2,color = 'green')
  #              p += line(DiscretePlotData,color = 'blue' )

            p.save('./out/LongRunComp/VIAComp-%s-%s-%s.pdf' %(testmu,testC,testR))


