# This file was *autogenerated* from the file GameExperiment.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_10 = Integer(10); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p0000000001 = RealNumber('0.0000000001')
import DiscountingGameSocial as Social
import DiscountingGameSelfish as Selfish
import random
if __name__ == "__main__":

    colors = rainbow(_sage_const_10 )
    while True:
        p = plot([],axes_labels = ['$\lambda$','PoA'])
        mu = random.uniform(_sage_const_0p5 ,_sage_const_1p5 )
        C = random.randint(_sage_const_1 ,_sage_const_1 )
        R = random.uniform(_sage_const_0p1 ,_sage_const_1 )
        for i in range(_sage_const_1 ,_sage_const_10 ):
            disc = i/_sage_const_10 

            PoA_data = []
            for e in range(_sage_const_1 ,_sage_const_100 ):
                print "Testing %s" %(e)

                SocialQueue = Social.Queue(e,mu,C,R,alpha = disc,epsilon = _sage_const_0p0000000001 )
                Dummy = SocialQueue.ValueIter()
                SocialVal =Dummy[_sage_const_0 ]['[0, 0]']

                SelfishQueue = Selfish.Queue(e,mu,C,R,alpha = disc,epsilon = _sage_const_0p0000000001 )
                Dummy2 = SelfishQueue.ValueIter()
                SelfishVal = Dummy2[_sage_const_0 ]['[0, 0]']
                print SelfishVal
                print SocialVal
                PoA_data.append([e,_sage_const_1 /(SelfishVal/SocialVal)])


            p += line(PoA_data,color = colors[i],legend_label = '$ \\alpha = %s $' %disc)

            p.save('./out/GameModel/PoALongRun-%s-%s-%s.pdf'%(mu,C,R))


