# This file was *autogenerated* from the file /home/c1012211/Static/MDP/Comparisons/Timings2.sage.
from sage.all_cmdline import *   # import sage library
import StaticHeuristic
import TwoQueueVia3 as TwoQueueVia
import Simm
import csv
import random
import time

@parallel
def func(n):
    #infile = open('./out/Timings.csv','rb')
    infile = open('./Static/MDP/Comparisons/out/Timings.csv','rb')
    data = csv.reader(infile)
    data = [row for row in data]
    infile.close()

    for row in data:

        e = eval(row[Integer(0)])
        lmbda = eval(row[Integer(1)])
        mu = [eval(row[Integer(2)]),eval(row[Integer(3)])]
        c = [eval(row[Integer(4)]),eval(row[Integer(5)])]
        skip = [eval(row[Integer(6)]),eval(row[Integer(7)])]

        print lmbda
        print mu
        print c
        print skip

        start = time.time()
        Object6 = StaticHeuristic.n2Ana(lmbda,mu,c,skip)
        N2Policy = Object6.calculate_D(e,e)
        N2time = time.time() - start

        Object7 = TwoQueueVia.Queue(lmbda,mu,c,skip,Policy = N2Policy)
        Object8 = Simm.RoutingSimm(lmbda,mu,c,skip,Integer(500),N2Policy,Integer(100),[Integer(0),Integer(0)],Policy_type = 'Matrix')
        N2Cost = Object7.VIA(RealNumber('0.1'))[Integer(0)]

        outfile = open('./Static/MDP/Comparisons/out/Timings2.csv','ab')
        #outfile = open('./out/Timings2.csv','ab')
        output = csv.writer(outfile)
        outrow = row + [N2Cost,Object8[Integer(0)],N2time,N2Policy.str()]

        output.writerow(outrow)
        outfile.close()

func(Integer(1))
